/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package tarik.LK.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class LoginApiV1TokenPostResponse {
    
    public String contentType;

    public LoginApiV1TokenPostResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * Validation Error
     */
    
    public tarik.LK.models.shared.HTTPValidationError httpValidationError;

    public LoginApiV1TokenPostResponse withHTTPValidationError(tarik.LK.models.shared.HTTPValidationError httpValidationError) {
        this.httpValidationError = httpValidationError;
        return this;
    }
    
    
    public Integer statusCode;

    public LoginApiV1TokenPostResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public LoginApiV1TokenPostResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Successful Response
     */
    
    public Object loginApiV1TokenPost200ApplicationJSONAny;

    public LoginApiV1TokenPostResponse withLoginApiV1TokenPost200ApplicationJSONAny(Object loginApiV1TokenPost200ApplicationJSONAny) {
        this.loginApiV1TokenPost200ApplicationJSONAny = loginApiV1TokenPost200ApplicationJSONAny;
        return this;
    }
    
    public LoginApiV1TokenPostResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
