/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package tarik.LK.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class OrderSchemaApiV1OrdersSchemaGetResponse {
    
    public String contentType;

    public OrderSchemaApiV1OrdersSchemaGetResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * Successful Response
     */
    
    public tarik.LK.models.shared.Response response;

    public OrderSchemaApiV1OrdersSchemaGetResponse withResponse(tarik.LK.models.shared.Response response) {
        this.response = response;
        return this;
    }
    
    
    public Integer statusCode;

    public OrderSchemaApiV1OrdersSchemaGetResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public OrderSchemaApiV1OrdersSchemaGetResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public OrderSchemaApiV1OrdersSchemaGetResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
