/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package tarik.LK.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class StatusRequestValidatedApiV1OrdersOrderIdStatusRequestPostResponse {
    
    public String contentType;

    public StatusRequestValidatedApiV1OrdersOrderIdStatusRequestPostResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * Validation Error
     */
    
    public tarik.LK.models.shared.HTTPValidationError httpValidationError;

    public StatusRequestValidatedApiV1OrdersOrderIdStatusRequestPostResponse withHTTPValidationError(tarik.LK.models.shared.HTTPValidationError httpValidationError) {
        this.httpValidationError = httpValidationError;
        return this;
    }
    
    /**
     * Successful Response
     */
    
    public tarik.LK.models.shared.Response response;

    public StatusRequestValidatedApiV1OrdersOrderIdStatusRequestPostResponse withResponse(tarik.LK.models.shared.Response response) {
        this.response = response;
        return this;
    }
    
    
    public Integer statusCode;

    public StatusRequestValidatedApiV1OrdersOrderIdStatusRequestPostResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public StatusRequestValidatedApiV1OrdersOrderIdStatusRequestPostResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public StatusRequestValidatedApiV1OrdersOrderIdStatusRequestPostResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
