/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package tarik.LK.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class StatusSchemaApiV1OrdersStatusSchemaGetResponse {
    
    public String contentType;

    public StatusSchemaApiV1OrdersStatusSchemaGetResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * Successful Response
     */
    
    public tarik.LK.models.shared.Response response;

    public StatusSchemaApiV1OrdersStatusSchemaGetResponse withResponse(tarik.LK.models.shared.Response response) {
        this.response = response;
        return this;
    }
    
    
    public Integer statusCode;

    public StatusSchemaApiV1OrdersStatusSchemaGetResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public StatusSchemaApiV1OrdersStatusSchemaGetResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public StatusSchemaApiV1OrdersStatusSchemaGetResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
