/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package tarik.LK.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import tarik.LK.utils.SpeakeasyMetadata;

public class TicketStatusApiV1TicketTicketIdCommentPostRequest {
    @SpeakeasyMetadata("request:mediaType=application/json")
    public tarik.LK.models.shared.OrderTicket orderTicket;

    public TicketStatusApiV1TicketTicketIdCommentPostRequest withOrderTicket(tarik.LK.models.shared.OrderTicket orderTicket) {
        this.orderTicket = orderTicket;
        return this;
    }
    
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=ticket_id")
    public String ticketId;

    public TicketStatusApiV1TicketTicketIdCommentPostRequest withTicketId(String ticketId) {
        this.ticketId = ticketId;
        return this;
    }
    
    public TicketStatusApiV1TicketTicketIdCommentPostRequest(@JsonProperty("OrderTicket") tarik.LK.models.shared.OrderTicket orderTicket, @JsonProperty("ticket_id") String ticketId) {
        this.orderTicket = orderTicket;
        this.ticketId = ticketId;
  }
}
