/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package tarik.LK.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import tarik.LK.utils.SpeakeasyMetadata;

public class TicketStatusApiV1TicketTicketIdCommentPostSecurity {
    @SpeakeasyMetadata("security:scheme=true,type=oauth2,name=Authorization")
    public String oAuth2PasswordBearer;

    public TicketStatusApiV1TicketTicketIdCommentPostSecurity withOAuth2PasswordBearer(String oAuth2PasswordBearer) {
        this.oAuth2PasswordBearer = oAuth2PasswordBearer;
        return this;
    }
    
    public TicketStatusApiV1TicketTicketIdCommentPostSecurity(@JsonProperty("OAuth2PasswordBearer") String oAuth2PasswordBearer) {
        this.oAuth2PasswordBearer = oAuth2PasswordBearer;
  }
}
