/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package tarik.LK;

import com.fasterxml.jackson.databind.ObjectMapper;
import java.net.http.HttpResponse;
import java.nio.charset.StandardCharsets;
import tarik.LK.utils.HTTPClient;
import tarik.LK.utils.HTTPRequest;
import tarik.LK.utils.JSON;
import tarik.LK.utils.SerializedBody;

public class Authentication {
	
	private SDKConfiguration sdkConfiguration;

	public Authentication(SDKConfiguration sdkConfiguration) {
		this.sdkConfiguration = sdkConfiguration;
	}

    /**
     * Login
     * @param request the request object containing all of the parameters for the API call
     * @return the response from the API call
     * @throws Exception if the API call fails
     */
    public tarik.LK.models.operations.LoginApiV1TokenPostResponse loginApiV1TokenPost(tarik.LK.models.shared.BodyLoginApiV1TokenPost request) throws Exception {
        String baseUrl = this.sdkConfiguration.serverUrl;
        String url = tarik.LK.utils.Utils.generateURL(baseUrl, "/api/v1/token");
        
        HTTPRequest req = new HTTPRequest();
        req.setMethod("POST");
        req.setURL(url);
        SerializedBody serializedRequestBody = tarik.LK.utils.Utils.serializeRequestBody(request, "request", "form");
        if (serializedRequestBody == null) {
            throw new Exception("Request body is required");
        }
        req.setBody(serializedRequestBody);

        req.addHeader("Accept", "application/json;q=1, application/json;q=0");
        req.addHeader("user-agent", String.format("speakeasy-sdk/%s %s %s %s", this.sdkConfiguration.language, this.sdkConfiguration.sdkVersion, this.sdkConfiguration.genVersion, this.sdkConfiguration.openapiDocVersion));
        
        HTTPClient client = this.sdkConfiguration.defaultClient;
        HttpResponse<byte[]> httpRes = client.send(req);

        String contentType = httpRes.headers().firstValue("Content-Type").orElse("application/octet-stream");

        tarik.LK.models.operations.LoginApiV1TokenPostResponse res = new tarik.LK.models.operations.LoginApiV1TokenPostResponse(contentType, httpRes.statusCode()) {{
            loginApiV1TokenPost200ApplicationJSONAny = null;
            httpValidationError = null;
        }};
        res.rawResponse = httpRes;
        
        if (httpRes.statusCode() == 200) {
            if (tarik.LK.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                Object out = mapper.readValue(new String(httpRes.body(), StandardCharsets.UTF_8), Object.class);
                res.loginApiV1TokenPost200ApplicationJSONAny = out;
            }
        }
        else if (httpRes.statusCode() == 422) {
            if (tarik.LK.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                tarik.LK.models.shared.HTTPValidationError out = mapper.readValue(new String(httpRes.body(), StandardCharsets.UTF_8), tarik.LK.models.shared.HTTPValidationError.class);
                res.httpValidationError = out;
            }
        }

        return res;
    }
}