/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package tarik.LK;

import com.fasterxml.jackson.databind.ObjectMapper;
import java.net.http.HttpResponse;
import java.nio.charset.StandardCharsets;
import tarik.LK.utils.HTTPClient;
import tarik.LK.utils.HTTPRequest;
import tarik.LK.utils.JSON;
import tarik.LK.utils.SerializedBody;

public class OrderTicket {
	
	private SDKConfiguration sdkConfiguration;

	public OrderTicket(SDKConfiguration sdkConfiguration) {
		this.sdkConfiguration = sdkConfiguration;
	}

    /**
     * Add new order ticket
     * @param request the request object containing all of the parameters for the API call
     * @param security the security details to use for authentication
     * @return the response from the API call
     * @throws Exception if the API call fails
     */
    public tarik.LK.models.operations.NewTicketApiV1TicketPostResponse newTicketApiV1TicketPost(tarik.LK.models.shared.OrderTicket request, tarik.LK.models.operations.NewTicketApiV1TicketPostSecurity security) throws Exception {
        String baseUrl = this.sdkConfiguration.serverUrl;
        String url = tarik.LK.utils.Utils.generateURL(baseUrl, "/api/v1/ticket");
        
        HTTPRequest req = new HTTPRequest();
        req.setMethod("POST");
        req.setURL(url);
        SerializedBody serializedRequestBody = tarik.LK.utils.Utils.serializeRequestBody(request, "request", "json");
        if (serializedRequestBody == null) {
            throw new Exception("Request body is required");
        }
        req.setBody(serializedRequestBody);

        req.addHeader("Accept", "application/json;q=1, application/json;q=0");
        req.addHeader("user-agent", String.format("speakeasy-sdk/%s %s %s %s", this.sdkConfiguration.language, this.sdkConfiguration.sdkVersion, this.sdkConfiguration.genVersion, this.sdkConfiguration.openapiDocVersion));
        
        HTTPClient client = tarik.LK.utils.Utils.configureSecurityClient(this.sdkConfiguration.defaultClient, security);
        
        HttpResponse<byte[]> httpRes = client.send(req);

        String contentType = httpRes.headers().firstValue("Content-Type").orElse("application/octet-stream");

        tarik.LK.models.operations.NewTicketApiV1TicketPostResponse res = new tarik.LK.models.operations.NewTicketApiV1TicketPostResponse(contentType, httpRes.statusCode()) {{
            response = null;
            httpValidationError = null;
        }};
        res.rawResponse = httpRes;
        
        if (httpRes.statusCode() == 200) {
            if (tarik.LK.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                tarik.LK.models.shared.Response out = mapper.readValue(new String(httpRes.body(), StandardCharsets.UTF_8), tarik.LK.models.shared.Response.class);
                res.response = out;
            }
        }
        else if (httpRes.statusCode() == 401) {
        }
        else if (httpRes.statusCode() == 422) {
            if (tarik.LK.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                tarik.LK.models.shared.HTTPValidationError out = mapper.readValue(new String(httpRes.body(), StandardCharsets.UTF_8), tarik.LK.models.shared.HTTPValidationError.class);
                res.httpValidationError = out;
            }
        }

        return res;
    }

    /**
     * Add ticket comment
     * @param request the request object containing all of the parameters for the API call
     * @param security the security details to use for authentication
     * @return the response from the API call
     * @throws Exception if the API call fails
     */
    public tarik.LK.models.operations.TicketStatusApiV1TicketTicketIdCommentPostResponse ticketStatusApiV1TicketTicketIdCommentPost(tarik.LK.models.operations.TicketStatusApiV1TicketTicketIdCommentPostRequest request, tarik.LK.models.operations.TicketStatusApiV1TicketTicketIdCommentPostSecurity security) throws Exception {
        String baseUrl = this.sdkConfiguration.serverUrl;
        String url = tarik.LK.utils.Utils.generateURL(tarik.LK.models.operations.TicketStatusApiV1TicketTicketIdCommentPostRequest.class, baseUrl, "/api/v1/ticket/{ticket_id}/comment", request, null);
        
        HTTPRequest req = new HTTPRequest();
        req.setMethod("POST");
        req.setURL(url);
        SerializedBody serializedRequestBody = tarik.LK.utils.Utils.serializeRequestBody(request, "orderTicket", "json");
        if (serializedRequestBody == null) {
            throw new Exception("Request body is required");
        }
        req.setBody(serializedRequestBody);

        req.addHeader("Accept", "application/json;q=1, application/json;q=0");
        req.addHeader("user-agent", String.format("speakeasy-sdk/%s %s %s %s", this.sdkConfiguration.language, this.sdkConfiguration.sdkVersion, this.sdkConfiguration.genVersion, this.sdkConfiguration.openapiDocVersion));
        
        HTTPClient client = tarik.LK.utils.Utils.configureSecurityClient(this.sdkConfiguration.defaultClient, security);
        
        HttpResponse<byte[]> httpRes = client.send(req);

        String contentType = httpRes.headers().firstValue("Content-Type").orElse("application/octet-stream");

        tarik.LK.models.operations.TicketStatusApiV1TicketTicketIdCommentPostResponse res = new tarik.LK.models.operations.TicketStatusApiV1TicketTicketIdCommentPostResponse(contentType, httpRes.statusCode()) {{
            response = null;
            httpValidationError = null;
        }};
        res.rawResponse = httpRes;
        
        if (httpRes.statusCode() == 200) {
            if (tarik.LK.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                tarik.LK.models.shared.Response out = mapper.readValue(new String(httpRes.body(), StandardCharsets.UTF_8), tarik.LK.models.shared.Response.class);
                res.response = out;
            }
        }
        else if (httpRes.statusCode() == 401) {
        }
        else if (httpRes.statusCode() == 422) {
            if (tarik.LK.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                tarik.LK.models.shared.HTTPValidationError out = mapper.readValue(new String(httpRes.body(), StandardCharsets.UTF_8), tarik.LK.models.shared.HTTPValidationError.class);
                res.httpValidationError = out;
            }
        }

        return res;
    }
}