/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package tarik.LK.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;
import tarik.LK.utils.SpeakeasyMetadata;

public class BodyLoginApiV1TokenPost {
    @SpeakeasyMetadata("form:name=client_id")
    public String clientId;

    public BodyLoginApiV1TokenPost withClientId(String clientId) {
        this.clientId = clientId;
        return this;
    }
    
    @SpeakeasyMetadata("form:name=client_secret")
    public String clientSecret;

    public BodyLoginApiV1TokenPost withClientSecret(String clientSecret) {
        this.clientSecret = clientSecret;
        return this;
    }
    
    @SpeakeasyMetadata("form:name=grant_type")
    public String grantType;

    public BodyLoginApiV1TokenPost withGrantType(String grantType) {
        this.grantType = grantType;
        return this;
    }
    
    @SpeakeasyMetadata("form:name=password")
    public String password;

    public BodyLoginApiV1TokenPost withPassword(String password) {
        this.password = password;
        return this;
    }
    
    @SpeakeasyMetadata("form:name=scope")
    public String scope;

    public BodyLoginApiV1TokenPost withScope(String scope) {
        this.scope = scope;
        return this;
    }
    
    @SpeakeasyMetadata("form:name=username")
    public String username;

    public BodyLoginApiV1TokenPost withUsername(String username) {
        this.username = username;
        return this;
    }
    
    public BodyLoginApiV1TokenPost(@JsonProperty("username") String username, @JsonProperty("password") String password) {
        this.username = username;
        this.password = password;
  }
}
