/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package tarik.LK.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Customer - Represents info about order customer
 */
public class Customer {
    @JsonProperty("email")
    public String email;

    public Customer withEmail(String email) {
        this.email = email;
        return this;
    }
    
    /**
     * This field could be numeric string
     */
    @JsonProperty("erp_id")
    public Long erpId;

    public Customer withErpId(Long erpId) {
        this.erpId = erpId;
        return this;
    }
    
    @JsonProperty("first_name")
    public String firstName;

    public Customer withFirstName(String firstName) {
        this.firstName = firstName;
        return this;
    }
    
    /**
     * This field could be numeric string
     */
    @JsonProperty("human_id")
    public Long humanId;

    public Customer withHumanId(Long humanId) {
        this.humanId = humanId;
        return this;
    }
    
    /**
     * This field could be numeric string
     */
    @JsonProperty("id")
    public Long id;

    public Customer withId(Long id) {
        this.id = id;
        return this;
    }
    
    @JsonProperty("last_name")
    public String lastName;

    public Customer withLastName(String lastName) {
        this.lastName = lastName;
        return this;
    }
    
    @JsonProperty("middle_name")
    public String middleName;

    public Customer withMiddleName(String middleName) {
        this.middleName = middleName;
        return this;
    }
    
    @JsonProperty("phone")
    public String phone;

    public Customer withPhone(String phone) {
        this.phone = phone;
        return this;
    }
    
    public Customer(@JsonProperty("email") String email, @JsonProperty("erp_id") Long erpId, @JsonProperty("first_name") String firstName, @JsonProperty("human_id") Long humanId, @JsonProperty("id") Long id, @JsonProperty("last_name") String lastName, @JsonProperty("middle_name") String middleName, @JsonProperty("phone") String phone) {
        this.email = email;
        this.erpId = erpId;
        this.firstName = firstName;
        this.humanId = humanId;
        this.id = id;
        this.lastName = lastName;
        this.middleName = middleName;
        this.phone = phone;
  }
}
