/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package tarik.LK.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * HTTPValidationError - Validation Error
 */
public class HTTPValidationError {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("detail")
    public ValidationError[] detail;

    public HTTPValidationError withDetail(ValidationError[] detail) {
        this.detail = detail;
        return this;
    }
    
    public HTTPValidationError(){}
}
