/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package tarik.LK.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * NPPackStation - Represents info about shipping via `Nova Posta PackStation` method
 */
public class NPPackStation {
    @JsonProperty("city")
    public String city;

    public NPPackStation withCity(String city) {
        this.city = city;
        return this;
    }
    
    @JsonProperty("city_id")
    public String cityId;

    public NPPackStation withCityId(String cityId) {
        this.cityId = cityId;
        return this;
    }
    
    @JsonProperty("comment")
    public String comment;

    public NPPackStation withComment(String comment) {
        this.comment = comment;
        return this;
    }
    
    @JsonProperty("region")
    public String region;

    public NPPackStation withRegion(String region) {
        this.region = region;
        return this;
    }
    
    @JsonProperty("region_id")
    public String regionId;

    public NPPackStation withRegionId(String regionId) {
        this.regionId = regionId;
        return this;
    }
    
    @JsonProperty("settlement_description")
    public String settlementDescription;

    public NPPackStation withSettlementDescription(String settlementDescription) {
        this.settlementDescription = settlementDescription;
        return this;
    }
    
    @JsonProperty("settlement_type")
    public String settlementType;

    public NPPackStation withSettlementType(String settlementType) {
        this.settlementType = settlementType;
        return this;
    }
    
    /**
     * Represents info about street
     */
    @JsonProperty("street")
    public Street street;

    public NPPackStation withStreet(Street street) {
        this.street = street;
        return this;
    }
    
    @JsonProperty("warehouse_id")
    public String warehouseId;

    public NPPackStation withWarehouseId(String warehouseId) {
        this.warehouseId = warehouseId;
        return this;
    }
    
    /**
     * This field could be numeric string
     */
    @JsonProperty("warehouse_number")
    public Long warehouseNumber;

    public NPPackStation withWarehouseNumber(Long warehouseNumber) {
        this.warehouseNumber = warehouseNumber;
        return this;
    }
    
    public NPPackStation(@JsonProperty("city") String city, @JsonProperty("city_id") String cityId, @JsonProperty("comment") String comment, @JsonProperty("region") String region, @JsonProperty("region_id") String regionId, @JsonProperty("settlement_description") String settlementDescription, @JsonProperty("settlement_type") String settlementType, @JsonProperty("street") Street street, @JsonProperty("warehouse_id") String warehouseId, @JsonProperty("warehouse_number") Long warehouseNumber) {
        this.city = city;
        this.cityId = cityId;
        this.comment = comment;
        this.region = region;
        this.regionId = regionId;
        this.settlementDescription = settlementDescription;
        this.settlementType = settlementType;
        this.street = street;
        this.warehouseId = warehouseId;
        this.warehouseNumber = warehouseNumber;
  }
}
