/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package tarik.LK.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * OrderTicketStatus - An enumeration.
 */
public enum OrderTicketStatus {
    AE5F2F10_F46B1410_FD9A0050BA5D6C38("ae5f2f10-f46b-1410-fd9a-0050ba5d6c38"),
    SEVENE9F1204_F46B1410_FB9A0050BA5D6C38("7e9f1204-f46b-1410-fb9a-0050ba5d6c38"),
    THREEE7F420C_F46B1410_FC9A0050BA5D6C38("3e7f420c-f46b-1410-fc9a-0050ba5d6c38"),
    AE7F411E_F46B1410009B0050BA5D6C38("ae7f411e-f46b-1410-009b-0050ba5d6c38"),
    THREE_THOUSAND_EIGHT_HUNDRED_AND_FIFTY_NINEC6E7_CBCB486B_BA5377808FE6E593("3859c6e7-cbcb-486b-ba53-77808fe6e593"),
    SIXE5F4218_F46B1410_FE9A0050BA5D6C38("6e5f4218-f46b-1410-fe9a-0050ba5d6c38");

    @JsonValue
    public final String value;

    private OrderTicketStatus(String value) {
        this.value = value;
    }
}
