/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package tarik.LK.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

public enum OrderStatuses {
    ZERO(0L),
    ONE(1L);

    @JsonValue
    public final Long value;

    private OrderStatuses(Long value) {
        this.value = value;
    }
}
