/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package tarik.LK.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.time.OffsetDateTime;
import tarik.LK.utils.DateTimeDeserializer;
import tarik.LK.utils.DateTimeSerializer;

public class OrderTicket {
    /**
     * Decision
     */
    @JsonProperty("decision")
    public String decision;

    public OrderTicket withDecision(String decision) {
        this.decision = decision;
        return this;
    }
    
    /**
     * Marketplace Order ID
     */
    @JsonProperty("order_id")
    public Long orderId;

    public OrderTicket withOrderId(Long orderId) {
        this.orderId = orderId;
        return this;
    }
    
    /**
     * Format YYYY-MM-DD[T]HH:MM
     */
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("solution_time")
    public OffsetDateTime solutionTime;

    public OrderTicket withSolutionTime(OffsetDateTime solutionTime) {
        this.solutionTime = solutionTime;
        return this;
    }
    
    /**
     * Status
     */
    @JsonProperty("status")
    public OrderTicketStatus status;

    public OrderTicket withStatus(OrderTicketStatus status) {
        this.status = status;
        return this;
    }
    
    /**
     * BPM ticket ID
     */
    @JsonProperty("ticket_id")
    public String ticketId;

    public OrderTicket withTicketId(String ticketId) {
        this.ticketId = ticketId;
        return this;
    }
    
    public OrderTicket(@JsonProperty("decision") String decision, @JsonProperty("order_id") Long orderId, @JsonProperty("solution_time") OffsetDateTime solutionTime, @JsonProperty("status") OrderTicketStatus status, @JsonProperty("ticket_id") String ticketId) {
        this.decision = decision;
        this.orderId = orderId;
        this.solutionTime = solutionTime;
        this.status = status;
        this.ticketId = ticketId;
  }
}
