/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package tarik.LK.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * OrderStatus - Represents info about new order status
 */
public class OrderStatus {
    /**
     * This field could be numeric string
     */
    @JsonProperty("order_id")
    public Long orderId;

    public OrderStatus withOrderId(Long orderId) {
        this.orderId = orderId;
        return this;
    }
    
    /**
     * This field could be numeric string
     */
    @JsonProperty("status")
    public OrderStatuses status;

    public OrderStatus withStatus(OrderStatuses status) {
        this.status = status;
        return this;
    }
    
    public OrderStatus(@JsonProperty("order_id") Long orderId, @JsonProperty("status") OrderStatuses status) {
        this.orderId = orderId;
        this.status = status;
  }
}
