/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package tarik.LK.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Payment - Represents info about order payment
 */
public class Payment {
    /**
     * This field could be numeric string
     */
    @JsonProperty("method")
    public PaymentMethod method;

    public Payment withMethod(PaymentMethod method) {
        this.method = method;
        return this;
    }
    
    /**
     * This field could be numeric string
     */
    @JsonProperty("status")
    public PaymentStatus status;

    public Payment withStatus(PaymentStatus status) {
        this.status = status;
        return this;
    }
    
    public Payment(@JsonProperty("method") PaymentMethod method, @JsonProperty("status") PaymentStatus status) {
        this.method = method;
        this.status = status;
  }
}
