/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package tarik.LK.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * PaymentStatus - An enumeration.
 */
public enum PaymentStatus {
    ZERO(0L);

    @JsonValue
    public final Long value;

    private PaymentStatus(Long value) {
        this.value = value;
    }
}
