/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package tarik.LK.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * PaymentMethod - An enumeration.
 */
public enum PaymentMethod {
    ZERO(0L),
    ONE(1L);

    @JsonValue
    public final Long value;

    private PaymentMethod(Long value) {
        this.value = value;
    }
}
