/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package tarik.LK.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Recipient - Represents info about recipient
 */
public class Recipient {
    @JsonProperty("first_name")
    public String firstName;

    public Recipient withFirstName(String firstName) {
        this.firstName = firstName;
        return this;
    }
    
    @JsonProperty("last_name")
    public String lastName;

    public Recipient withLastName(String lastName) {
        this.lastName = lastName;
        return this;
    }
    
    @JsonProperty("middle_name")
    public String middleName;

    public Recipient withMiddleName(String middleName) {
        this.middleName = middleName;
        return this;
    }
    
    @JsonProperty("phone")
    public String phone;

    public Recipient withPhone(String phone) {
        this.phone = phone;
        return this;
    }
    
    public Recipient(@JsonProperty("first_name") String firstName, @JsonProperty("last_name") String lastName, @JsonProperty("middle_name") String middleName, @JsonProperty("phone") String phone) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.middleName = middleName;
        this.phone = phone;
  }
}
