/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package tarik.LK.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Shipping - Represents info about shipping order
 */
public class Shipping {
    /**
     * Represents info about shipping via `Nova Posta PackStation` method
     */
    @JsonProperty("address")
    public NPPackStation address;

    public Shipping withAddress(NPPackStation address) {
        this.address = address;
        return this;
    }
    
    @JsonProperty("method")
    public ShippingMethod method;

    public Shipping withMethod(ShippingMethod method) {
        this.method = method;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("price")
    public Double price;

    public Shipping withPrice(Double price) {
        this.price = price;
        return this;
    }
    
    /**
     * Represents info about recipient
     */
    @JsonProperty("recipient")
    public Recipient recipient;

    public Shipping withRecipient(Recipient recipient) {
        this.recipient = recipient;
        return this;
    }
    
    public Shipping(@JsonProperty("address") NPPackStation address, @JsonProperty("method") ShippingMethod method, @JsonProperty("recipient") Recipient recipient) {
        this.address = address;
        this.method = method;
        this.recipient = recipient;
  }
}
