/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package tarik.LK.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

public enum ShippingMethod {
    NOVAPOSHTA_PACKSTATION("novaposhta_packstation");

    @JsonValue
    public final String value;

    private ShippingMethod(String value) {
        this.value = value;
    }
}
