/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package tarik.LK.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Street - Represents info about street
 */
public class Street {
    @JsonProperty("name")
    public String name;

    public Street withName(String name) {
        this.name = name;
        return this;
    }
    
    public Street(@JsonProperty("name") String name) {
        this.name = name;
  }
}
